name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Start environment
      run: npm start &
    - name: Run tests
      run: npm test
    - name: Cypress
      run: $(npm bin)/cypress run --record
