name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: node:15-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: npm ci
    - name: Start environment
      run: npm start &
    - name: Run tests
      run: npm test
    - name: Cypress
      run: $(npm bin)/cypress run --record
