name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Install
      run: npm ci
    - name: Start environment
      run: npm start &
    - name: Run tests
      run: npm test
    - name: Cypress
      run: $(npm bin)/cypress run
